### ISSUE TITLE
java.lang.ClassNotFoundException: org.codehaus.plexus.classworlds.realm.ClassRealm

### ISSUE THREAD

**Issue by ksaito1125** [making/spring-boot-docker-blank#2]
``` bash
$ mvn archetype:generate -B -DarchetypeGroupId=am.ik.archetype -DarchetypeArtifactId=spring-boot-docker-blank-archetype -DarchetypeVersion=1.0.5 -DgroupId=jp.sample -DartifactId=sbsample
$ cd sbsample/
$ mvn clean package -e
...
Caused by: org.codehaus.plexus.component.factory.ComponentInstantiationException: Could not instanciate component: role: 'org.codehaus.plexus.component.configurator.ComponentConfigurator', implementation: 'org.codehaus.plexus.component.configurator.BasicComponentConfigurator', role hint: 'basic'
        at org.codehaus.plexus.component.factory.java.JavaComponentFactory.makeException(JavaComponentFactory.java:77)
        at org.codehaus.plexus.component.factory.java.JavaComponentFactory.newInstance(JavaComponentFactory.java:62)
        at org.codehaus.plexus.DefaultPlexusContainer.createComponentInstance(DefaultPlexusContainer.java:1464)
        at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:93)
        at org.codehaus.plexus.component.manager.ClassicSingletonComponentManager.getComponent(ClassicSingletonComponentManager.java:92)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:331)
        ... 21 more
Caused by: java.lang.NoClassDefFoundError: org/codehaus/plexus/classworlds/realm/ClassRealm
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.newInstance(Class.java:412)
        at org.codehaus.plexus.component.factory.java.JavaComponentFactory.newInstance(JavaComponentFactory.java:44)
        ... 25 more
Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.classworlds.realm.ClassRealm
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.codehaus.classworlds.RealmClassLoader.loadClassDirect(RealmClassLoader.java:195)
        at org.codehaus.classworlds.DefaultClassRealm.loadClass(DefaultClassRealm.java:255)
        at org.codehaus.classworlds.DefaultClassRealm.loadClass(DefaultClassRealm.java:274)
        at org.codehaus.classworlds.RealmClassLoader.loadClass(RealmClassLoader.java:214)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 30 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6 seconds
[INFO] Finished at: Sun Aug 16 09:25:42 JST 2015
[INFO] Final Memory: 38M/91M
[INFO] ------------------------------------------------------------------------
$
```

**Comment by making** [comment]
Can you show the whole result of `mvn -X compile` ？
I need which version of your mvn and jdk are.

**Comment by ksaito1125** [comment]
Thank you very much.
I was using the Maven2.
I will try to upgrade later .

**Comment by making** [comment]
I'm afraid this archetype doesn't support maven2. I've never tried yet.
Can you use Maven3 instead?

**Comment by ksaito1125** [comment]
I installed the maven3 and openjdk1.8.
I was able to run as README.

``` bash
vagrant@trusty64:~/git/springboot-sample$ mvn -X clean package
Maven home: /home/vagrant/pub/apache/maven/apache-maven-3.3.3
Java version: 1.8.0_45-internal, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: ja_JP, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-59-generic", arch: "amd64", family: "unix"
...
[INFO] Executing tasks
Build sequence for target(s) `main' is [main]
Complete build sequence is [main, ]

main:
fileset: Setup scanner in dir /home/vagrant/git/springboot-sample/target with patternSet{ includes: [Dockerfile, Dockerrun.aws.json, springboot-sample.jar] excludes: [] }
      [zip] Building zip: /home/vagrant/git/springboot-sample/target/app.zip
      [zip] adding entry Dockerfile
      [zip] adding entry Dockerrun.aws.json
      [zip] adding entry springboot-sample.jar
[INFO] Executed tasks
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23.517 s
[INFO] Finished at: 2015-08-17T10:39:57+09:00
[INFO] Final Memory: 21M/50M
[INFO] ------------------------------------------------------------------------
```

Thank you very much.

**Comment by making** [comment]
Have a nice time :)
